### PR TITLE
Attempts to fix the relative velocity of released cargo by using VESS…

### PR DESCRIPTION
**Pull request by amaudsley**
…ELSTATUS.

### CODE REVIEW

**Comment by amaudsley** [comment]
Note that in this implementation the relative velocity is simply +Y ('up') relative to the vessel, a more robust implementation would use the direction of the attachment point to account for different cargo orientations etc. This should be a simple enough change to make to the code, rather than using the fixed _V(0,$velocity,0) vector we'd use orientationVector * $velocity.

**Comment by abdullah-radwan** [comment]
Thank you for your help. I'll use what I can do with that.

**Comment by abdullah-radwan** [comment]
Unforutanly your code didn't work well. It places the cargo on some crazy trajectories. That's due to the use of Local2Rel function, which was useless. This code works well:

```
	CargoVessel* cargo = static_cast<CargoVessel*>(oapiGetVesselInterface(pair.second));

	if (vessel->GroundContact()); // Release when on ground
	else {
		cargoReleased = vessel->DetachChild(attachsMap[pair.first]);

		VESSELSTATUS2 status;
		memset(&status, 0, sizeof(status));
		status.version = 2;
		cargo->GetStatusEx(&status);

		status.rvel.y += releaseVel;

		cargo->DefSetStateEx(&status);
	}
```

Anyway, thank you for your help (you gave me the idea of using VESSELSTATUS for that).

**Comment by amaudsley** [comment]
Odd, I took that right from the HCLV (it's used for the booster separation) where it works fine; at least it put you on the right track!

**Comment by abdullah-radwan** [comment]
In Alpha 3, I recalculated the attachment point and DetachChild now works.

For the orientation, it's always Y for the cargo. It's the vessel author responsibility to rotate the attachment point accordingly, so Y point in the correct direction.

**Pull request merged**
